name = "beakspeak"
compatibility_date = "2026-04-14"

routes = [
  { pattern = "unformedideas.com/beakspeak", zone_name = "unformedideas.com" },
  { pattern = "unformedideas.com/beakspeak/*", zone_name = "unformedideas.com" },
  { pattern = "www.unformedideas.com/beakspeak", zone_name = "unformedideas.com" },
  { pattern = "www.unformedideas.com/beakspeak/*", zone_name = "unformedideas.com" },
  { pattern = "beakspeak.app", custom_domain = true },
  { pattern = "www.beakspeak.app", custom_domain = true },
]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
